package mtr;

import mtr.block.*;
import mtr.data.TransportMode;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;


public interface Blocks {

	BrandNewEpicRegistryObject<Block> APG_DOOR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockAPGDoor(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> APG_GLASS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockAPGGlass(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> APG_GLASS_END = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockAPGGlassEnd(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ARRIVAL_PROJECTOR_1_SMALL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockArrivalProjector1Small(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ARRIVAL_PROJECTOR_1_MEDIUM = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockArrivalProjector1Medium(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ARRIVAL_PROJECTOR_1_LARGE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockArrivalProjector1Large(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> CEILING = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockCeilingAuto(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 15)));
	BrandNewEpicRegistryObject<Block> CEILING_LIGHT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockCeiling(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 15)));
	BrandNewEpicRegistryObject<Block> CEILING_NO_LIGHT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockCeiling(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> CLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockClock(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 5)));
	BrandNewEpicRegistryObject<Block> CLOCK_POLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockClockPole(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> ESCALATOR_SIDE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockEscalatorSide(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ESCALATOR_STEP = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockEscalatorStep(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_CIO = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_CKT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_HEO = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_MOS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_PLAIN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_SHM = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_STAINED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_STW = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_TSH = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> GLASS_FENCE_WKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockGlassFence(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LOGO = new BrandNewEpicRegistryObject<>(resourceKey -> new Block(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 10)));
	BrandNewEpicRegistryObject<Block> LIFT_BUTTONS_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftButtons(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_PANEL_EVEN_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftPanelEven1(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_PANEL_ODD_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftPanelOdd1(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_PANEL_EVEN_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftPanelEven2(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_PANEL_ODD_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftPanelOdd2(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_TRACK_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftTrack(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_TRACK_FLOOR_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftTrackFloor(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_DOOR_EVEN_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftDoor(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> LIFT_DOOR_ODD_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockLiftDoorOdd(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> MARBLE_BLUE = new BrandNewEpicRegistryObject<>(resourceKey -> new Block(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> MARBLE_BLUE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new SlabBlock(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> MARBLE_SANDY = new BrandNewEpicRegistryObject<>(resourceKey -> new Block(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> MARBLE_SANDY_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new SlabBlock(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> METAL = new BrandNewEpicRegistryObject<>(resourceKey -> new Block(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> METAL_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new SlabBlock(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> MOSAIC_TILE = new BrandNewEpicRegistryObject<>(resourceKey -> new Block(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> MOSAIC_TILE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new SlabBlock(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> PIDS_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDS1(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> PIDS_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDS2(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> PIDS_3 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDS3(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> PIDS_4 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDS4(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> PIDS_SINGLE_ARRIVAL_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDSSingleArrival1(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> PIDS_POLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPIDSPole(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1)));
	BrandNewEpicRegistryObject<Block> PLATFORM = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2), false));
	BrandNewEpicRegistryObject<Block> PLATFORM_INDENTED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), true));
	BrandNewEpicRegistryObject<Block> PLATFORM_NA_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2), false));
	BrandNewEpicRegistryObject<Block> PLATFORM_NA_1_INDENTED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), true));
	BrandNewEpicRegistryObject<Block> PLATFORM_NA_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2), false));
	BrandNewEpicRegistryObject<Block> PLATFORM_NA_2_INDENTED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), true));
	BrandNewEpicRegistryObject<Block> PLATFORM_UK_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2), false));
	BrandNewEpicRegistryObject<Block> PLATFORM_UK_1_INDENTED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPlatform(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), true));
	BrandNewEpicRegistryObject<Block> PSD_DOOR_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDDoor(createProperties(resourceKey), 0));
	BrandNewEpicRegistryObject<Block> PSD_GLASS_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDGlass(createProperties(resourceKey), 0));
	BrandNewEpicRegistryObject<Block> PSD_GLASS_END_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDGlassEnd(createProperties(resourceKey), 0));
	BrandNewEpicRegistryObject<Block> PSD_DOOR_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDDoor(createProperties(resourceKey), 1));
	BrandNewEpicRegistryObject<Block> PSD_GLASS_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDGlass(createProperties(resourceKey), 1));
	BrandNewEpicRegistryObject<Block> PSD_GLASS_END_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDGlassEnd(createProperties(resourceKey), 1));
	BrandNewEpicRegistryObject<Block> PSD_TOP = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockPSDTop(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> RAIL_NODE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode(createProperties(resourceKey), TransportMode.TRAIN));
	BrandNewEpicRegistryObject<Block> FREE_NODE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockFreeNode(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> BOAT_NODE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode.BlockBoatNode(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> CABLE_CAR_NODE_LOWER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode.BlockContinuousMovementNode(createProperties(resourceKey), false, false));
	BrandNewEpicRegistryObject<Block> CABLE_CAR_NODE_UPPER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode.BlockContinuousMovementNode(createProperties(resourceKey), true, false));
	BrandNewEpicRegistryObject<Block> CABLE_CAR_NODE_STATION = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode.BlockContinuousMovementNode(createProperties(resourceKey), false, true));
	BrandNewEpicRegistryObject<Block> AIRPLANE_NODE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockNode(createProperties(resourceKey), TransportMode.AIRPLANE));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_2_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 2, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_2_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 2, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_3_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 3, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_3_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 3, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_4_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 4, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_4_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 4, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_5_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 5, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_5_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 5, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_6_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 6, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_6_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 6, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_7_EVEN = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 7, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_7_ODD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 7, true));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_MIDDLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySign(createProperties(resourceKey), 0, false));
	BrandNewEpicRegistryObject<Block> RAILWAY_SIGN_POLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRailwaySignPole(createProperties(resourceKey).requiresCorrectToolForDrops().strength(1).noOcclusion()));
	BrandNewEpicRegistryObject<Block> ROUTE_SIGN_STANDING_LIGHT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRouteSignStandingLight(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ROUTE_SIGN_STANDING_METAL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRouteSignStandingMetal(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ROUTE_SIGN_WALL_LIGHT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRouteSignWallLight(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> ROUTE_SIGN_WALL_METAL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRouteSignWallMetal(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> RUBBISH_BIN_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockRubbishBin(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_2_ASPECT_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight2Aspect1(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_2_ASPECT_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight2Aspect2(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_2_ASPECT_3 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight2Aspect3(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_2_ASPECT_4 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight2Aspect4(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_3_ASPECT_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight3Aspect1(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_3_ASPECT_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight3Aspect2(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_4_ASPECT_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight4Aspect1(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_LIGHT_4_ASPECT_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalLight4Aspect2(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_SEMAPHORE_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalSemaphore1(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_SEMAPHORE_2 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockSignalSemaphore2(createProperties(resourceKey).strength(4)));
	BrandNewEpicRegistryObject<Block> SIGNAL_POLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorPole(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), false));

	BrandNewEpicRegistryObject<Block> STATION_COLOR_ANDESITE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.ANDESITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BEDROCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BIRCH_WOOD = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.BIRCH_WOOD)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BONE_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.BONE_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CHISELED_QUARTZ_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CHISELED_QUARTZ_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CHISELED_STONE_BRICKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CHISELED_STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CLAY = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CLAY)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_COAL_ORE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.COAL_ORE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_COBBLESTONE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.COBBLESTONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CONCRETE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_CONCRETE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CONCRETE_POWDER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_CONCRETE_POWDER)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CRACKED_STONE_BRICKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CRACKED_STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_DARK_PRISMARINE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.DARK_PRISMARINE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_DIORITE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.DIORITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_GRAVEL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.GRAVEL)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_IRON_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.IRON_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_METAL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 10)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_MOSAIC_TILE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PLANKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.OAK_PLANKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_POLE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorPole(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion(), true));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_POLISHED_ANDESITE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.POLISHED_ANDESITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_POLISHED_DIORITE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.POLISHED_DIORITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PURPUR_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.PURPUR_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PURPUR_PILLAR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.PURPUR_PILLAR)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_BRICKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_PILLAR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_PILLAR)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SMOOTH_QUARTZ = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.SMOOTH_QUARTZ)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SMOOTH_STONE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.SMOOTH_STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SNOW_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_WOOL)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STAINED_GLASS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorGlass(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_STAINED_GLASS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STONE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STONE_BRICKS = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_WOOL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColor(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_WOOL)));

	BrandNewEpicRegistryObject<Block> STATION_COLOR_ANDESITE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.ANDESITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BEDROCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BIRCH_WOOD_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.BIRCH_WOOD)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_BONE_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.BONE_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CHISELED_QUARTZ_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CHISELED_QUARTZ_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CHISELED_STONE_BRICKS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CHISELED_STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CLAY_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CLAY)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_COAL_ORE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.COAL_ORE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_COBBLESTONE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.COBBLESTONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CONCRETE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_CONCRETE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CONCRETE_POWDER_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_CONCRETE_POWDER)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_CRACKED_STONE_BRICKS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.CRACKED_STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_DARK_PRISMARINE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.DARK_PRISMARINE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_DIORITE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.DIORITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_GRAVEL_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.GRAVEL)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_IRON_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.IRON_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_METAL_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 10)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_MOSAIC_TILE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PLANKS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.OAK_PLANKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_POLISHED_ANDESITE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.POLISHED_ANDESITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_POLISHED_DIORITE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.POLISHED_DIORITE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PURPUR_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.PURPUR_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_PURPUR_PILLAR_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.PURPUR_PILLAR)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_BLOCK)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_BRICKS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_QUARTZ_PILLAR_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.QUARTZ_PILLAR)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SMOOTH_QUARTZ_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.SMOOTH_QUARTZ)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SMOOTH_STONE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.SMOOTH_STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_SNOW_BLOCK_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_WOOL)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STAINED_GLASS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorGlassSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_STAINED_GLASS).noOcclusion()));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STONE_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_STONE_BRICKS_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.STONE_BRICKS)));
	BrandNewEpicRegistryObject<Block> STATION_COLOR_WOOL_SLAB = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationColorSlab(copyProperties(resourceKey, net.minecraft.world.level.block.Blocks.WHITE_WOOL)));

	BrandNewEpicRegistryObject<Block> STATION_NAME_ENTRANCE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameEntrance(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion()));
	BrandNewEpicRegistryObject<Block> STATION_NAME_TALL_BLOCK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameTallBlock(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> STATION_NAME_TALL_BLOCK_DOUBLE_SIDED = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameTallBlockDoubleSided(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> STATION_NAME_TALL_WALL = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameTallWall(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> STATION_NAME_WALL_WHITE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameWallWhite(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion()));
	BrandNewEpicRegistryObject<Block> STATION_NAME_WALL_GRAY = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameWallGray(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion()));
	BrandNewEpicRegistryObject<Block> STATION_NAME_WALL_BLACK = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockStationNameWallBlack(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion()));
	BrandNewEpicRegistryObject<Block> TACTILE_MAP = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTactileMap(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).noOcclusion()));
	BrandNewEpicRegistryObject<Block> TICKET_BARRIER_ENTRANCE_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketBarrier(createProperties(resourceKey), true));
	BrandNewEpicRegistryObject<Block> TICKET_BARRIER_EXIT_1 = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketBarrier(createProperties(resourceKey), false));
	BrandNewEpicRegistryObject<Block> TICKET_MACHINE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketMachine(createProperties(resourceKey).requiresCorrectToolForDrops().strength(2).lightLevel(state -> 5).noOcclusion()));
	BrandNewEpicRegistryObject<Block> TICKET_PROCESSOR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketProcessor(createProperties(resourceKey), true, true, true));
	BrandNewEpicRegistryObject<Block> TICKET_PROCESSOR_ENTRANCE = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketProcessor(createProperties(resourceKey), true, true, false));
	BrandNewEpicRegistryObject<Block> TICKET_PROCESSOR_EXIT = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketProcessor(createProperties(resourceKey), true, false, true));
	BrandNewEpicRegistryObject<Block> TICKET_PROCESSOR_ENQUIRY = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTicketProcessorEnquiry(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> TRAIN_ANNOUNCER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTrainAnnouncer(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> TRAIN_CARGO_LOADER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTrainCargoLoader(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> TRAIN_CARGO_UNLOADER = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTrainCargoUnloader(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> TRAIN_REDSTONE_SENSOR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTrainRedstoneSensor(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Block> TRAIN_SCHEDULE_SENSOR = new BrandNewEpicRegistryObject<>(resourceKey -> new BlockTrainScheduleSensor(createProperties(resourceKey)));

	static BlockBehaviour.Properties createProperties(ResourceKey<Block> resourceKey) {
		return BlockBehaviour.Properties.of().setId(resourceKey);
	}

	static BlockBehaviour.Properties copyProperties(ResourceKey<Block> resourceKey, Block block) {
		return BlockBehaviour.Properties.ofFullCopy(block).setId(resourceKey);
	}
}
