package mtr;

import mtr.data.RailType;
import mtr.data.TransportMode;
import mtr.item.*;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;

public interface Items {

	BrandNewEpicRegistryObject<Item> APG_DOOR = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_DOOR, ItemPSDAPGBase.EnumPSDAPGType.APG));
	BrandNewEpicRegistryObject<Item> APG_GLASS = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS, ItemPSDAPGBase.EnumPSDAPGType.APG));
	BrandNewEpicRegistryObject<Item> APG_GLASS_END = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS_END, ItemPSDAPGBase.EnumPSDAPGType.APG));
	BrandNewEpicRegistryObject<Item> BRUSH = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemWithCreativeTabBase(createProperties(resourceKey), Keys.LIFTS_ONLY ? CreativeModeTabs.ESCALATORS_LIFTS : CreativeModeTabs.CORE, propModifier -> propModifier.stacksTo(1)));
	BrandNewEpicRegistryObject<Item> RAILWAY_DASHBOARD = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemDashboard(createProperties(resourceKey), TransportMode.TRAIN));
	BrandNewEpicRegistryObject<Item> BOAT_DASHBOARD = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemDashboard(createProperties(resourceKey), TransportMode.BOAT));
	BrandNewEpicRegistryObject<Item> CABLE_CAR_DASHBOARD = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemDashboard(createProperties(resourceKey), TransportMode.CABLE_CAR));
	BrandNewEpicRegistryObject<Item> AIRPLANE_DASHBOARD = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemDashboard(createProperties(resourceKey), TransportMode.AIRPLANE));
	BrandNewEpicRegistryObject<Item> DRIVER_KEY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemWithCreativeTabBase(createProperties(resourceKey), CreativeModeTabs.CORE, propModifier -> propModifier.stacksTo(1)));
	BrandNewEpicRegistryObject<Item> BOAT_NODE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemWithCreativeTabBase.ItemPlaceOnWater(createProperties(resourceKey), CreativeModeTabs.CORE, Blocks.BOAT_NODE.get()));
	BrandNewEpicRegistryObject<Item> ESCALATOR = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemEscalator(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Item> LIFT_BUTTONS_LINK_CONNECTOR = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemLiftButtonsLinkModifier(createProperties(resourceKey),true));
	BrandNewEpicRegistryObject<Item> LIFT_BUTTONS_LINK_REMOVER = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemLiftButtonsLinkModifier(createProperties(resourceKey),false));
	BrandNewEpicRegistryObject<Item> LIFT_DOOR_1 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_DOOR, ItemPSDAPGBase.EnumPSDAPGType.LIFT_DOOR_1));
	BrandNewEpicRegistryObject<Item> LIFT_DOOR_ODD_1 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_DOOR, ItemPSDAPGBase.EnumPSDAPGType.LIFT_DOOR_ODD_1));
	BrandNewEpicRegistryObject<Item> LIFT_REFRESHER = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemLiftRefresher(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Item> PSD_DOOR_1 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_DOOR, ItemPSDAPGBase.EnumPSDAPGType.PSD_1));
	BrandNewEpicRegistryObject<Item> PSD_GLASS_1 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS, ItemPSDAPGBase.EnumPSDAPGType.PSD_1));
	BrandNewEpicRegistryObject<Item> PSD_GLASS_END_1 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS_END, ItemPSDAPGBase.EnumPSDAPGType.PSD_1));
	BrandNewEpicRegistryObject<Item> PSD_DOOR_2 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_DOOR, ItemPSDAPGBase.EnumPSDAPGType.PSD_2));
	BrandNewEpicRegistryObject<Item> PSD_GLASS_2 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS, ItemPSDAPGBase.EnumPSDAPGType.PSD_2));
	BrandNewEpicRegistryObject<Item> PSD_GLASS_END_2 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemPSDAPGBase(createProperties(resourceKey), ItemPSDAPGBase.EnumPSDAPGItem.PSD_APG_GLASS_END, ItemPSDAPGBase.EnumPSDAPGType.PSD_2));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_20 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.WOODEN));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_20_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.WOODEN));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_40 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.STONE));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_40_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.STONE));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_60 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.EMERALD));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_60_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.EMERALD));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_80 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.IRON));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_80_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.IRON));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_120 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.OBSIDIAN));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_120_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.OBSIDIAN));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_160 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.BLAZE));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_160_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.BLAZE));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_200 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.QUARTZ));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_200_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.QUARTZ));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_300 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.DIAMOND));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_300_ONE_WAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, true, RailType.DIAMOND));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_PLATFORM = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, true, true, false, RailType.PLATFORM));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_SIDING = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, true, true, false, RailType.SIDING));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_TURN_BACK = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), true, false, true, false, RailType.TURN_BACK));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_CABLE_CAR = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), false, true, false, true, RailType.CABLE_CAR));
	BrandNewEpicRegistryObject<Item> RAIL_CONNECTOR_RUNWAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey), false, false, true, true, RailType.RUNWAY));
	BrandNewEpicRegistryObject<Item> RAIL_REMOVER = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemRailModifier(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Item> RESOURCE_PACK_CREATOR = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemResourcePackCreator(createProperties(resourceKey)));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_WHITE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.WHITE));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_ORANGE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.ORANGE));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_MAGENTA = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.MAGENTA));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_LIGHT_BLUE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.LIGHT_BLUE));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_YELLOW = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.YELLOW));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_LIME = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.LIME));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_PINK = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.PINK));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_GRAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.GRAY));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_LIGHT_GRAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.LIGHT_GRAY));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_CYAN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.CYAN));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_PURPLE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.PURPLE));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_BLUE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.BLUE));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_BROWN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.BROWN));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_GREEN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.GREEN));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_RED = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.RED));
	BrandNewEpicRegistryObject<Item> SIGNAL_CONNECTOR_BLACK = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), true, DyeColor.BLACK));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_WHITE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.WHITE));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_ORANGE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.ORANGE));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_MAGENTA = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.MAGENTA));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_LIGHT_BLUE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.LIGHT_BLUE));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_YELLOW = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.YELLOW));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_LIME = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.LIME));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_PINK = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.PINK));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_GRAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.GRAY));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_LIGHT_GRAY = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.LIGHT_GRAY));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_CYAN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.CYAN));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_PURPLE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.PURPLE));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_BLUE = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.BLUE));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_BROWN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.BROWN));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_GREEN = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.GREEN));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_RED = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.RED));
	BrandNewEpicRegistryObject<Item> SIGNAL_REMOVER_BLACK = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemSignalModifier(createProperties(resourceKey), false, DyeColor.BLACK));
	BrandNewEpicRegistryObject<Item> BRIDGE_CREATOR_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemBridgeCreator(createProperties(resourceKey), 3));
	BrandNewEpicRegistryObject<Item> BRIDGE_CREATOR_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemBridgeCreator(createProperties(resourceKey), 5));
	BrandNewEpicRegistryObject<Item> BRIDGE_CREATOR_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemBridgeCreator(createProperties(resourceKey), 7));
	BrandNewEpicRegistryObject<Item> BRIDGE_CREATOR_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemBridgeCreator(createProperties(resourceKey), 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_4_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 4, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_4_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 4, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_4_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 4, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_4_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 4, 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_5_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 5, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_5_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 5, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_5_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 5, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_5_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 5, 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_6_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 6, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_6_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 6, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_6_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 6, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_CREATOR_6_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelCreator(createProperties(resourceKey), 6, 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_4_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 4, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_4_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 4, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_4_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 4, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_4_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 4, 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_5_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 5, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_5_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 5, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_5_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 5, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_5_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 5, 9));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_6_3 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 6, 3));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_6_5 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 6, 5));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_6_7 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 6, 7));
	BrandNewEpicRegistryObject<Item> TUNNEL_WALL_CREATOR_6_9 = new BrandNewEpicRegistryObject<>((resourceKey) -> new ItemTunnelWallCreator(createProperties(resourceKey), 6, 9));

	static Item.Properties createProperties(ResourceKey<Item> key) {
		return new Item.Properties().setId(key);
	}
}
